In [1]:
import pandas as pd
import numpy as np

In [2]:
calendar = pd.read_csv('./AirbnbData/calendar-Sydney.csv.gz')
listings = pd.read_csv('./AirbnbData/listings-Sydney.csv.gz')
reviews = pd.read_csv('./AirbnbData/reviews-Sydney.csv.gz')
dictionary = pd.read_excel('./AirbnbData/DataDictionary.xlsx', skiprows=3, header=0)

C:\Users\18205\AppData\Local\Temp\ipykernel_7972\1883027626.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  calendar = pd.read_csv('./AirbnbData/calendar-Sydney.csv.gz')

看起来是飞机的日程安排，available用于确定当天是否有飞行任务

In [14]:
calendar.head(20)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,11156,2024-03-18,f,$65.00,NaN,90,180
1,11156,2024-03-19,t,$65.00,NaN,90,180
2,11156,2024-03-20,t,$65.00,NaN,90,180
3,11156,2024-03-21,t,$65.00,NaN,90,180
4,11156,2024-03-22,t,$65.00,NaN,90,180
5,11156,2024-03-23,t,$65.00,NaN,90,180
6,11156,2024-03-24,t,$65.00,NaN,90,180
7,11156,2024-03-25,t,$65.00,NaN,90,180
8,11156,2024-03-26,t,$65.00,NaN,90,180
9,11156,2024-03-27,t,$65.00,NaN,90,180
10,11156,2024-03-28,t,$65.00,NaN,90,180
11,11156,2024-03-29,t,$65.00,NaN,90,180
12,11156,2024-03-30,t,$65.00,NaN,90,180
13,11156,2024-03-31,t,$65.00,NaN,90,180
14,11156,2024-04-01,t,$65.00,NaN,90,180
15,11156,2024-04-02,t,$65.00,NaN,90,180
16,11156,2024-04-03,t,$65.00,NaN,90,180
17,11156,2024-04-04,t,$65.00,NaN,90,180
18,11156,2024-04-05,t,$65.00,NaN,90,180
19,11156,2024-04-06,t,$65.00,NaN,90,180

In [9]:
calendar.shape

(5210010, 7)

listings的内容似乎相当杂，包含了绝大多数信息

In [4]:
listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1050164598350388320,https://www.airbnb.com/rooms/1050164598350388320,20240316023820,2024-03-18,city scrape,Self service English breakfast,Close to transport airport older style unit ne...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,211218678,...,NaN,NaN,NaN,PID-STRA-61891,f,1,0,1,0,NaN
1,1096082243192434668,https://www.airbnb.com/rooms/1096082243192434668,20240316023820,2024-03-18,city scrape,Apartment in Rushcutters Bay,Full 2 bedroom apartment with balcony. Walking...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,26721338,...,NaN,NaN,NaN,Exempt,f,2,1,1,0,NaN
2,2167538,https://www.airbnb.com/rooms/2167538,20240316023820,2024-03-18,city scrape,"Modern Sydney home near beach,shops",**Availability extremely flexible**<br /><br /...,Queens Park is a safe and friendly neighbourho...,https://a0.muscache.com/pictures/29922910/2399...,11059668,...,5.00,5.00,4.00,NaN,f,1,1,0,0,0.01
3,790607305500629830,https://www.airbnb.com/rooms/790607305500629830,20240316023820,2024-03-18,city scrape,Luxury double room,Relax in this tranquil and stylish space.,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,202112801,...,4.77,4.68,4.68,PID-STRA-21723,f,30,5,25,0,2.13
4,641106357139201992,https://www.airbnb.com/rooms/641106357139201992,20240316023820,2024-03-18,city scrape,Chic Studio Apartment in Prime Bondi Location,Immerse yourself in the vibrant atmosphere of ...,Bondi is one of Australia’s most iconic suburb...,https://a0.muscache.com/pictures/prohost-api/H...,279001183,...,3.94,4.94,4.29,PID-STRA-36651,f,217,217,0,0,0.84

In [10]:
listings.shape

(14274, 75)

In [5]:
listings.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

review 似乎是客户评价

In [6]:
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,11156,19220,2009-12-05,52946,Jeff,Colleen was friendly and very helpful regardin...
1,11156,32592,2010-03-31,99382,Michael,"Great place, centrally located, easy walk to t..."
2,11156,42280,2010-05-14,105797,Marina,Colleen is very friendly and helpful. The apar...
3,11156,140942,2010-11-17,259213,Sigrid,Dear Colleen!\r<br/>My friend Diemut from Germ...
4,11156,151966,2010-12-11,273389,Eduardo,"Lovely, interesting chats and very helpful giv..."

In [11]:
reviews.shape

(499595, 6)

看起来是对listings的列的解释

In [15]:
dictionary.head(60)

,Field,Type,Calculated,Description,Reference
0,id,integer,NaN,Airbnb's unique identifier for the listing,NaN
1,listing_url,text,y,URL of the listing,NaN
2,last_scraped,datetime,y,"UTC. The date and time this listing was ""scrap...",NaN
3,name,text,NaN,Name of the listing,NaN
4,description,text,NaN,Detailed description of the listing,NaN
5,neighborhood_overview,text,NaN,Host's description of the neighbourhood,NaN
6,picture_url,text,NaN,URL to the Airbnb hosted regular sized image f...,NaN
7,host_id,integer,NaN,Airbnb's unique identifier for the host/user,NaN
8,host_url,text,y,The Airbnb page for the host,NaN
9,host_name,text,NaN,Name of the host. Usually just the first name(s).,NaN
10,host_since,date,NaN,The date the host/user was created. For hosts ...,NaN
11,host_about,text,NaN,Description about the host,NaN
12,host_response_time,text,NaN,The time lag the host promise to respond messa...,NaN
13,host_response_rate,numeric,NaN,The rate at which the host respond messages.,NaN
14,host_acceptance_rate,numeric,NaN,That rate at which the host accepts booking re...,NaN
15,host_is_superhost,boolean [t=true; f=false],NaN,Whether the host is a superhost,NaN
16,host_total_listings_count,integer,NaN,The number of listings the host has (per Airbn...,NaN
17,host_identity_verified,boolean [t=true; f=false],NaN,Whether the host's identity has been verified,NaN
18,neighbourhood,text,y,The neighbourhood as geocoded using the latitu...,NaN
19,latitude,numeric,NaN,Uses the World Geodetic System (WGS84) project...,NaN
20,longitude,numeric,NaN,Uses the World Geodetic System (WGS84) project...,NaN
21,property_type,text,NaN,Self selected property type. Hotels and Bed an...,NaN
22,room_type,text,NaN,[Entire home/apt|Private room|Shared room|Hote...,https://www.airbnb.com/help/article/5/what-doe...
23,accommodates,integer,NaN,The maximum capacity of the listing,NaN
24,bathrooms_text,string,NaN,The number of bathrooms in the listing. \nOn t...,NaN
25,bedrooms,integer,NaN,The number of bedrooms,NaN
26,beds,integer,NaN,The number of bed(s),NaN
27,amenities,json,NaN,The amenities offered by the listing.,NaN
28,price,currency,NaN,daily price in local currency,NaN
29,minimum_nights,integer,NaN,minimum number of night stay for the listing (...,NaN
30,maximum_nights,integer,NaN,maximum number of night stay for the listing (...,NaN
31,minimum_minimum_nights,integer,y,the smallest minimum_night value from the cale...,NaN
32,maximum_minimum_nights,integer,y,the largest minimum_night value from the calen...,NaN
33,minimum_maximum_nights,integer,y,the smallest maximum_night value from the cale...,NaN
34,maximum_maximum_nights,integer,y,the largest maximum_night value from the calen...,NaN
35,minimum_nights_avg_ntm,numeric,y,the average minimum_night value from the calen...,NaN
36,maximum_nights_avg_ntm,numeric,y,the average maximum_night value from the calen...,NaN
37,has_availability,boolean [t=true; f=false],NaN,Whether the listing has availability information,NaN
38,availability_30,integer,y,avaliability_x. The availability of the listin...,NaN
39,availability_60,integer,y,avaliability_x. The availability of the listin...,NaN
40,availability_90,integer,y,avaliability_x. The availability of the listin...,NaN
41,availability_365,integer,y,avaliability_x. The availability of the listin...,NaN
42,number_of_reviews,integer,NaN,The number of reviews the listing has,NaN
43,number_of_reviews_ltm,integer,y,The number of reviews the listing has (in the ...,NaN
44,number_of_reviews_l30d,integer,y,The number of reviews the listing has (in the ...,NaN
45,first_review,date,y,The date of the first/oldest review,NaN
46,last_review,date,y,The date of the last/newest review,NaN
47,review_scores_rating,numeric,NaN,The average review score on the overall rating...,NaN
48,review_scores_accuracy,numeric,NaN,The average review score on the description ac...,NaN
49,review_scores_cleanliness,numeric,NaN,The average review score on the cleanliness of...,NaN
50,review_scores_checkin,numeric,NaN,The average review score on the checkin conven...,NaN
51,review_scores_communication,numeric,NaN,The average review score on the communication ...,NaN
52,review_scores_location,numeric,NaN,The average review score on the location of th...,NaN
53,review_scores_value,numeric,NaN,The average review score on the value of the l...,NaN
54,instant_bookable,boolean [t=true; f=false],NaN,Whether the guest can automatically book the l...,NaN
55,calculated_host_listings_count,integer,y,The number of listings the host has in the cur...,NaN
56,calculated_host_listings_count_entire_homes,integer,y,The number of Entire home/apt listings the hos...,NaN
57,calculated_host_listings_count_private_rooms,integer,y,The number of Private room listings the host h...,NaN
58,calculated_host_listings_count_shared_rooms,integer,y,The number of Shared room listings the host ha...,NaN
59,reviews_per_month,numeric,y,The number of reviews the listing has over the...,NaN

In [12]:
dictionary.shape

(60, 5)

In [18]:
col_listings = listings.columns.tolist()
col_dic = dictionary['Field'].tolist()
col_listings.sort()
col_dic.sort()

In [25]:
i = 0
extra_name = []
for index, name in enumerate(col_listings):
    if i < len(col_dic):
        if name == col_dic[i]:
            print(f"{index}: {name} -- {i}:{col_dic[i]}")
            i += 1
        else :
            extra_name.append(name)
            print(f"{index}: {name}")
    else:
        print(f"{index}: {name}")

0: accommodates -- 0:accommodates
1: amenities -- 1:amenities
2: availability_30 -- 2:availability_30
3: availability_365 -- 3:availability_365
4: availability_60 -- 4:availability_60
5: availability_90 -- 5:availability_90
6: bathrooms
7: bathrooms_text -- 6:bathrooms_text
8: bedrooms -- 7:bedrooms
9: beds -- 8:beds
10: calculated_host_listings_count -- 9:calculated_host_listings_count
11: calculated_host_listings_count_entire_homes -- 10:calculated_host_listings_count_entire_homes
12: calculated_host_listings_count_private_rooms -- 11:calculated_host_listings_count_private_rooms
13: calculated_host_listings_count_shared_rooms -- 12:calculated_host_listings_count_shared_rooms
14: calendar_last_scraped
15: calendar_updated
16: description -- 13:description
17: first_review -- 14:first_review
18: has_availability -- 15:has_availability
19: host_about -- 16:host_about
20: host_acceptance_rate -- 17:host_acceptance_rate
21: host_has_profile_pic
22: host_id -- 18:host_id
23: host_identity_verified -- 19:host_identity_verified
24: host_is_superhost -- 20:host_is_superhost
25: host_listings_count
26: host_location
27: host_name -- 21:host_name
28: host_neighbourhood
29: host_picture_url
30: host_response_rate -- 22:host_response_rate
31: host_response_time -- 23:host_response_time
32: host_since -- 24:host_since
33: host_thumbnail_url
34: host_total_listings_count -- 25:host_total_listings_count
35: host_url -- 26:host_url
36: host_verifications
37: id -- 27:id
38: instant_bookable -- 28:instant_bookable
39: last_review -- 29:last_review
40: last_scraped -- 30:last_scraped
41: latitude -- 31:latitude
42: license
43: listing_url -- 32:listing_url
44: longitude -- 33:longitude
45: maximum_maximum_nights -- 34:maximum_maximum_nights
46: maximum_minimum_nights -- 35:maximum_minimum_nights
47: maximum_nights -- 36:maximum_nights
48: maximum_nights_avg_ntm -- 37:maximum_nights_avg_ntm
49: minimum_maximum_nights -- 38:minimum_maximum_nights
50: minimum_minimum_nights -- 39:minimum_minimum_nights
51: minimum_nights -- 40:minimum_nights
52: minimum_nights_avg_ntm -- 41:minimum_nights_avg_ntm
53: name -- 42:name
54: neighborhood_overview -- 43:neighborhood_overview
55: neighbourhood -- 44:neighbourhood
56: neighbourhood_cleansed
57: neighbourhood_group_cleansed
58: number_of_reviews -- 45:number_of_reviews
59: number_of_reviews_l30d -- 46:number_of_reviews_l30d
60: number_of_reviews_ltm -- 47:number_of_reviews_ltm
61: picture_url -- 48:picture_url
62: price -- 49:price
63: property_type -- 50:property_type
64: review_scores_accuracy -- 51:review_scores_accuracy
65: review_scores_checkin -- 52:review_scores_checkin
66: review_scores_cleanliness -- 53:review_scores_cleanliness
67: review_scores_communication -- 54:review_scores_communication
68: review_scores_location -- 55:review_scores_location
69: review_scores_rating -- 56:review_scores_rating
70: review_scores_value -- 57:review_scores_value
71: reviews_per_month -- 58:reviews_per_month
72: room_type -- 59:room_type
73: scrape_id
74: source

In [26]:
extra_name

['bathrooms',
 'calendar_last_scraped',
 'calendar_updated',
 'host_has_profile_pic',
 'host_listings_count',
 'host_location',
 'host_neighbourhood',
 'host_picture_url',
 'host_thumbnail_url',
 'host_verifications',
 'license',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed']